version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: product_db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U product_user -d product_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: product_api
    command: gunicorn -w 4 -b 0.0.0.0:5000 "src.app:create_app()"
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://product_user:product_password@postgres:5432/product_db
      - FLASK_ENV=production
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  postgres_data:

